### ISSUE TITLE
Add NASA funding test to acknowledgements.html page

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#111]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Blast is funded by a NASA grant. We should include that information on the acknowledgments page

---

## **Describe the solution you'd like**

* Change the acknowledgements.html pages to include some NASA funding text ("Blast is based upon work supported by the National Aeronautics and Space Administration under Grant No. 80NSSC21K0834 issued through the Astrophysics Data Analysis Program.") under the title after the "Blast is largely glue..." paragraph.

**Comment by Lila-braff** [comment]
I was having some trouble with this one just because I was trying to use slim_dev to see the addition on blast but it wouldn't work. I hope that this fixed the way that we wanted it to. Let me know if not and I will try again
