### ISSUE TITLE
[Bug] Dustmaps are loaded repeatatly on start up

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#126]
# **🐞 Bug Report**

## **Describe the bug**

* On start up of the slim or full dev stack the dust maps are repeated loaded and pollute the app start up messages, making them hard to read and understand, this also probably slows the start up time.

* I think these are the offending lines.(particularly the config reset). They should either be modified or placed within a function so they are only parsed when the function is called.

https://github.com/astrophpeter/blast/blob/a2c7bbf5a5037972eceb790e78c4510e1334ab88/app/host/host_utils.py#L38

*Success would be no dustmaps output in the terminal upon startup with slim or full dev.

**Comment by djones1040** [comment]
finally got this one done
