### ISSUE TITLE
Host photometry needs MW E(B-V) correction [Bug] 

### ISSUE THREAD

**Issue by djones1040** [scimma/blast#161]
# **🐞 Bug Report**
Host galaxy photometry isn't being corrected for Milky Way reddening

## **Describe the bug**

* need to use extinction module to correct for MW E(B-V) given by Schlafly & Finkbeiner estimates

---

### **Is this a regression?**

no
---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

*

---

### **Media prove**

---

### **Your environment**

* OS: 
* Node version:
* Npm version:
* Browser name and version:

---

### **Additional context**

*

**Comment by manning-ncsa** [comment]
This was fixed by #162 but the magic text in the PR description `Fixes #165, #164, #161` should have been `Fixes #165, Fixes #164, Fixes #161` to close it automatically.
