### ISSUE TITLE
[Bug] GALEX/MAST imaging queries are timing out

### ISSUE THREAD

**Issue by djones1040** [scimma/blast#265]
# **🐞 Bug Report**
We're failing to download GALEX images for a number of sources

## **Describe the bug**

* Blast freezes on processing cutout downloads for a number of transients.  Issue appears to trace back to galex image availability queries.  Doesn't seem to be a MAST server issue, seems to be massive number of results being returned in some queries, so we need to limit our queries to the galex collection.

---

### **Is this a regression?**

--- haven't noticed this in any previous version, but may have been present

**Comment by djones1040** [comment]
PR #266

**Comment by manning-ncsa** [comment]
@djones1040 Does your referenced merge request fix this bug? Should we close this?

**Comment by djones1040** [comment]
yeah sorry closing
