### ISSUE TITLE
Need a blast logo

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#35]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* We don't have a logo for blast! We really need one, and should put it everywhere!!!

---

## **Describe the solution you'd like**

* Design a logo for blast and put it on: 

1. The website header
2. The repository readme.md,
3. The documentation (by adding the html_logo = "path to file" line in the docs/config.py file). 

Please design one and post it here as an attachment to a comment. Once we are happy with the design add the file to the base directory of the project!

**Comment by manning-ncsa** [comment]
Here are some sketches I made a few years ago when I initially worked on this project:

<ol>
    <li><img src="https://github.com/astrophpeter/blast/assets/56734137/936f038b-7b5d-4b62-888e-0398a31e0d4b" width="200px" /></li>
    <li><img src="https://github.com/astrophpeter/blast/assets/56734137/05a21671-5d03-4ebc-a8ea-466fd714dfc9" width="200px" /></li>
    <li><img src="https://github.com/astrophpeter/blast/assets/56734137/cfe078e9-0dab-49a6-a486-c431608761ad" width="200px" /></li>
</ol>

**Comment by manning-ncsa** [comment]
Here's another concept:
![image](https://github.com/astrophpeter/blast/assets/56734137/05bd52a5-9b6a-46df-a544-3d159ab5f53b)

**Comment by djones1040** [comment]
nice!!!  yeah I really like #1 and the full-scale concept at the bottom.

**Comment by djones1040** [comment]
marking this one as done
