### ISSUE TITLE
Fix typos in the documentation

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#37]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* There are definitely typos in the documentation, we should fix them.

---

## **Describe the solution you'd like**

* Go to the files in docs/ and find and fix the typos! Look at the readthedoc auto build to check your work.

**Comment by manning-ncsa** [comment]
PR https://github.com/astrophpeter/blast/pull/195 includes many spelling and grammar corrections.

@djones1040 I recommend closing this issue.
