### ISSUE TITLE
Add funding information to acknowledgements page 

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#39]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Blast is funded by a NASA grant. We should include that information in the documentation 

---

## **Describe the solution you'd like**

* Change the contributors.rst pages to include some NASA funding text ("Blast is based upon work supported by the National Aeronautics and Space Administration under Grant No. 80NSSC21K0834 issued through the Astrophysics Data Analysis Program.") under the title and before the paragraph starting "Blast is developed..")

**Comment by astrophpeter** [comment]
@djones1040 could you paste the appropriate NASA funding acknowledgement text here, so I can assign this issue? :)

**Comment by djones1040** [comment]
Hey, I think this will work: This material is based upon work supported by the National Aeronautics and Space Administration under Grant No. 80NSSC21K0834 issued through the Astrophysics Data Analysis Program.
