### ISSUE TITLE
Get nginx to serve flower

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#43]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Currently flower (the celery monitoring dashboard can only be accessed by port (0.0.0.0:8888). In production we need to serve this page with ngnx with authentication (password protected).

---

## **Describe the solution you'd like**

* I want to be able access the flower dashboard at 0.0.0.0/flower/. 

* See here for a place to start: https://github.com/mher/flower/issues/762 or here https://stackoverflow.com/questions/19689510/celery-flower-security-in-production/61997024#61997024

* For putting an authentication layer around the flower dashboard see here https://flower.readthedocs.io/en/latest/auth.html

**Comment by manning-ncsa** [comment]
For the initial production deployment, I opted to use [a fully external method](https://gitlab.com/ncsa-blast/kubernetes/-/blob/main/charts/blast/templates/flower-reverse-proxy.yaml): an NGINX reverse proxy with OAuth2 Proxy middleware for OIDC authentication, currently via GitLab to match how we're authenticating to the ArgoCD instance controlling the Blast application deployment in Kubernetes.
