### ISSUE TITLE
Make TransientTaskRunner().run_process() return transient name and task status

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#44]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* In the celery monitoring dashboard (flower) the return of the tasks are shown. Currently the transient tasks do not return anything, this makes the flower dashboard hard to interpret. There is no way to tell which transient a particular task is being run on, knowing that info could help with debugging. 

---

## **Describe the solution you'd like**

* Make `TransientTaskRunner().run_process()` return transient name and task status message. This info will then be displayed on the flower dashboard which will make it whole lot more useful.

**Comment by manning-ncsa** [comment]
[This commit](https://github.com/astrophpeter/blast/commit/3127d070a90ef481634d098af7c5531389588d65) adds a return value of the transient name, but this is only displayed upon successful completion of a task. The underlying challenge here is that the tasks are periodic and not triggered by specific transients, so it is not clear whether it is possible to inform Flower of the transient information at runtime.

**Comment by manning-ncsa** [comment]
@djones1040 I am closing this as mostly solved by the commit mentioned above. Feel free to reopen it if you think it is worth pursuing further.
