### ISSUE TITLE
Add sherlock to match hosts to transients

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#47]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

*Currently blast only uses GHOST to match hosts galaxies to transients. We should include sherlock (https://github.com/thespacedoctor/sherlock) as well as a check on GHOST or to perform a match when GHOST fails. 

---

## **Describe the solution you'd like**

* Implement Sherlock by either:

1. Implement Sherlock within the GHOST task runner (and make the task runner a general host matcher which has some logic about how to use the results of both GHOST and Sherlock to match a host galaxy) 

2.  Make it a separate task runner that runs Sherlock when a GHOST match fails. With this method we many need to think about how to store two different host matches for a given transient (If GHOST and sherlock disagree)

**Comment by djones1040** [comment]
closing as I think GHOST has gotten really robust now
