### ISSUE TITLE
Finish implementing prospector

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#55]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Prospector is half implemented we need to finish it - including the front end!

---

## **Describe the solution you'd like**

* Prospector running in a TaskRunner, and front end posterior displays.

**Comment by djones1040** [comment]
https://github.com/astrophpeter/blast/pull/115

works, just need to do some front-end dev to see if model's getting stored in a way that it's usable.  Also needs a "fast" version for testing, test takes like 40 min.

**Comment by djones1040** [comment]
https://github.com/astrophpeter/blast/pull/115 now done I think, includes plotting
