### ISSUE TITLE
Fix broken DOI links in the acknowledgements table

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#62]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* links to the DOIs in the /acknowledgements page table table are broken, we should fix this.

* Fix this by moving the trailing / in the href string in this line

https://github.com/astrophpeter/blast/blob/a2c7bbf5a5037972eceb790e78c4510e1334ab88/app/host/templates/host/acknowledgements.html#L43

**Comment by manning-ncsa** [comment]
Discovered one broken DOI link and corrected it in commit https://github.com/astrophpeter/blast/commit/87675e0bd523f7c8508e5abc3bd4bdf49b202a2b.
