### ISSUE TITLE
Make the home page more interesting 

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#63]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* The blast home page is a bit boring, we should make it better. 

---

## **Describe the solution you'd like**

* Add pictures and text about SN and host galaxies!

**Comment by astrofoley** [comment]
It would be really nice to show global results such as SFR vs. mass for all objects, color-coded by SN type.

**Comment by manning-ncsa** [comment]
@djones1040 If we have no short-to-midterm plans to work on this, I recommend closing the issue as "not planned" and reopen it if we decide this is something we actually plan to do.

**Comment by djones1040** [comment]
a good idea, but not planned for now
