### ISSUE TITLE
Get dust information for a transient.

### ISSUE THREAD

**Issue by astrophpeter** [scimma/blast#67]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

*  We need ebv for each transients, I've started implementing here: https://github.com/astrophpeter/blast/blob/3bf2a3f515fcea52e6db4f41ef906e1669200777/app/host/host_utils.py#L204

---

## **Describe the solution you'd like**

* This should be wrapped in a TransientTaskRunner and added to the periodic tasks list.

**Comment by djones1040** [comment]
https://github.com/astrophpeter/blast/pull/81
